[package]

name = "ahrs"
version = "0.0.1"
authors = ["jmagnuson"]

[lib]
name = "ahrs"
path = "src/lib.rs"

[dependencies]
nalgebra = "0.10.*"

# Dev profile, used for `cargo build`
[profile.dev]
opt-level = 0 # 2  # Controls the --opt-level the compiler builds with
debug = true   # Controls whether the compiler passes -g or `--cfg ndebug`
