[package]

name = "ahrs"
version = "0.1.1"
authors = ["jmagnuson"]

description = "A Rust port of Madgwick's AHRS algorithm"
repository = "https://github.com/jmagnuson/ahrs-rs"
readme = "README.md"
keywords = ["ahrs", "madgwick", "imu", "kalman", "accelerometer"]
license = "GPL-3.0"

[lib]
name = "ahrs"
path = "src/lib.rs"

[dependencies]
nalgebra = "0.10.*"

[dev-dependencies]
rand = "0.3"

# Dev profile, used for `cargo build`
[profile.dev]
opt-level = 0  # Controls the --opt-level the compiler builds with
debug = true   # Controls whether the compiler passes -g or `--cfg ndebug`
