name: Test

on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust: [stable, beta, nightly]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install rust (${{ matrix.rust}})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Run cargo build
        run: cargo build --all-features --verbose

      - name: Run cargo test
        run: cargo test --all-features --verbose

      # Test no_std with release, which disables overflow checking
      - name: Run cargo test (no_std)
        run: cargo test --release --no-default-features --verbose
